'use client'

import Link from 'next/link'
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import ModuleAccessGuard from '@/components/ModuleAccessGuard'
import { supabase } from '@/lib/supabase/client'

const EMPRESA_KEY = 'empresa_activa_id'
const tipos = ['vacuna','vulvoplastia','curacion','tratamiento','desparasitacion','control','otro']
const unidades = ['ml','cc','unidad','dosis','gramo','litro','frasco','caja','otro']
const hoy = () => new Date().toISOString().slice(0,10)
const field = 'mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-100'
const money = (value:number) => new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:2}).format(value)
const date = (value:string|null) => value ? new Intl.DateTimeFormat('es-CL').format(new Date(`${value.slice(0,10)}T00:00:00`)) : '—'
const title = (value:string) => value.replaceAll('_',' ').replace(/^./,x=>x.toUpperCase())

type Animal={id:string;nombre:string;identificador:string|null;estado:string}
type Protocolo={id:string;nombre:string;tipo:string;activo:boolean}
type ProtocolItem={id:string;protocolo_id:string;insumo_id:string|null;descripcion:string;dosis:number|null;unidad:string|null}
type Insumo={id:string;nombre:string;unidad_medida:string;activo:boolean}
type Lote={id:string;insumo_id:string;numero_lote:string;fecha_vencimiento:string|null;cantidad_actual:number;costo_unitario:number|null;unidad:string|null;activo:boolean}
type Procedimiento={id:string;animal_id:string;protocolo_id:string|null;fecha:string;tipo:string;profesional:string|null;diagnostico:string|null;detalle:string|null;proximo_control:string|null;observaciones:string|null;estado:string;costo_total:number}
type Uso={id:string;procedimiento_id:string;insumo_id:string|null;lote_insumo_id:string|null;descripcion:string|null;cantidad:number;unidad:string|null;costo_unitario:number|null;costo_total:number|null;observaciones:string|null}
type Linea={key:string;insumo_id:string;lote_insumo_id:string;descripcion:string;cantidad:string;unidad:string;observaciones:string}
type Form={animal_id:string;protocolo_id:string;fecha:string;tipo:string;profesional:string;diagnostico:string;detalle:string;proximo_control:string;observaciones:string;estado:'borrador'|'registrado'}
const emptyForm=():Form=>({animal_id:'',protocolo_id:'',fecha:hoy(),tipo:'tratamiento',profesional:'',diagnostico:'',detalle:'',proximo_control:'',observaciones:'',estado:'registrado'})
const emptyLine=():Linea=>({key:crypto.randomUUID(),insumo_id:'',lote_insumo_id:'',descripcion:'',cantidad:'1',unidad:'ml',observaciones:''})

export default function ProcedimientosPage(){
  const [empresaId,setEmpresaId]=useState<string|null>(null)
  const [animales,setAnimales]=useState<Animal[]>([]),[protocolos,setProtocolos]=useState<Protocolo[]>([]),[protocolItems,setProtocolItems]=useState<ProtocolItem[]>([]),[insumos,setInsumos]=useState<Insumo[]>([]),[lotes,setLotes]=useState<Lote[]>([]),[procedimientos,setProcedimientos]=useState<Procedimiento[]>([]),[usos,setUsos]=useState<Uso[]>([])
  const [form,setForm]=useState<Form>(emptyForm),[lineas,setLineas]=useState<Linea[]>([]),[creating,setCreating]=useState(false),[detailId,setDetailId]=useState<string|null>(null)
  const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null),[success,setSuccess]=useState<string|null>(null)
  useEffect(()=>{const timer=setTimeout(()=>setEmpresaId(localStorage.getItem(EMPRESA_KEY)),0);return()=>clearTimeout(timer)},[])
  const load=useCallback(async()=>{if(!empresaId){setLoading(false);return}setLoading(true);setError(null)
    const [a,p,pi,i,l,pr,u]=await Promise.all([
      supabase.from('vet_animales').select('id,nombre,identificador,estado').eq('empresa_id',empresaId).order('nombre'),
      supabase.from('vet_protocolos').select('id,nombre,tipo,activo').eq('empresa_id',empresaId).order('nombre'),
      supabase.from('vet_protocolos_items').select('id,protocolo_id,insumo_id,descripcion,dosis,unidad').eq('empresa_id',empresaId).order('orden'),
      supabase.from('vet_insumos').select('id,nombre,unidad_medida,activo').eq('empresa_id',empresaId).order('nombre'),
      supabase.from('vet_lotes_insumo').select('id,insumo_id,numero_lote,fecha_vencimiento,cantidad_actual,costo_unitario,unidad,activo').eq('empresa_id',empresaId).order('fecha_vencimiento'),
      supabase.from('vet_procedimientos').select('id,animal_id,protocolo_id,fecha,tipo,profesional,diagnostico,detalle,proximo_control,observaciones,estado,costo_total').eq('empresa_id',empresaId).order('fecha',{ascending:false}),
      supabase.from('vet_procedimiento_insumos').select('id,procedimiento_id,insumo_id,lote_insumo_id,descripcion,cantidad,unidad,costo_unitario,costo_total,observaciones').eq('empresa_id',empresaId),
    ]);const failure=a.error||p.error||pi.error||i.error||l.error||pr.error||u.error;if(failure)setError(`No fue posible cargar los procedimientos: ${failure.message}`);else{
      setAnimales((a.data??[]) as Animal[]);setProtocolos((p.data??[]) as Protocolo[]);setProtocolItems((pi.data??[]).map(x=>({...x,dosis:x.dosis==null?null:Number(x.dosis)})) as ProtocolItem[]);setInsumos((i.data??[]) as Insumo[]);setLotes((l.data??[]).map(x=>({...x,cantidad_actual:Number(x.cantidad_actual),costo_unitario:x.costo_unitario==null?null:Number(x.costo_unitario)})) as Lote[]);setProcedimientos((pr.data??[]).map(x=>({...x,costo_total:Number(x.costo_total)})) as Procedimiento[]);setUsos((u.data??[]).map(x=>({...x,cantidad:Number(x.cantidad),costo_unitario:x.costo_unitario==null?null:Number(x.costo_unitario),costo_total:x.costo_total==null?null:Number(x.costo_total)})) as Uso[])}setLoading(false)},[empresaId])
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load])
  const animalNames=useMemo(()=>new Map(animales.map(x=>[x.id,x.nombre])),[animales]),protocolNames=useMemo(()=>new Map(protocolos.map(x=>[x.id,x.nombre])),[protocolos]),insumoNames=useMemo(()=>new Map(insumos.map(x=>[x.id,x.nombre])),[insumos]),loteNames=useMemo(()=>new Map(lotes.map(x=>[x.id,x.numero_lote])),[lotes])
  const detail=procedimientos.find(x=>x.id===detailId),detailUsos=usos.filter(x=>x.procedimiento_id===detailId)
  const lineCost=(line:Linea)=>{const lote=lotes.find(x=>x.id===line.lote_insumo_id);return Number(line.cantidad||0)*(lote?.costo_unitario??0)}
  const estimated=lineas.reduce((sum,line)=>sum+lineCost(line),0)
  function updateLine(key:string,patch:Partial<Linea>){setLineas(current=>current.map(x=>x.key===key?{...x,...patch}:x))}
  function selectProtocol(id:string){const protocol=protocolos.find(x=>x.id===id);setForm(current=>({...current,protocolo_id:id,tipo:protocol?.tipo??current.tipo}));setLineas(protocolItems.filter(x=>x.protocolo_id===id).map(x=>({key:crypto.randomUUID(),insumo_id:x.insumo_id??'',lote_insumo_id:'',descripcion:x.descripcion,cantidad:String(x.dosis??1),unidad:x.unidad==='cc'?'ml':x.unidad??'ml',observaciones:''})))}
  function selectInsumo(line:Linea,id:string){const item=insumos.find(x=>x.id===id);updateLine(line.key,{insumo_id:id,lote_insumo_id:'',descripcion:line.descripcion||item?.nombre||'',unidad:item?.unidad_medida==='cc'?'ml':item?.unidad_medida??line.unidad})}
  function validate(){if(!form.animal_id||!form.fecha||!form.tipo)return 'Animal, fecha y tipo son obligatorios.';for(const line of lineas){const qty=Number(line.cantidad);if(!Number.isFinite(qty)||qty<=0)return 'Todas las cantidades deben ser mayores a 0.';if(line.insumo_id&&!line.lote_insumo_id)return 'Selecciona un lote para cada insumo que consumirá stock.';if(!line.insumo_id&&!line.descripcion.trim())return 'Describe cada ítem manual.';const lote=lotes.find(x=>x.id===line.lote_insumo_id);if(lote&&form.estado==='registrado'&&qty>lote.cantidad_actual)return `Stock insuficiente en el lote ${lote.numero_lote}.`;if(lote?.fecha_vencimiento&&lote.fecha_vencimiento<form.fecha)return `El lote ${lote.numero_lote} está vencido para la fecha elegida.`}return null}
  async function save(e:FormEvent){e.preventDefault();if(!empresaId)return;const problem=validate();if(problem)return setError(problem);setSaving(true);setError(null);const {error:rpcError}=await supabase.rpc('vet_registrar_procedimiento_con_insumos',{p_empresa_id:empresaId,p_animal_id:form.animal_id,p_protocolo_id:form.protocolo_id||null,p_fecha:`${form.fecha}T12:00:00Z`,p_tipo:form.tipo,p_profesional:form.profesional,p_diagnostico:form.diagnostico,p_detalle:form.detalle,p_proximo_control:form.proximo_control||null,p_observaciones:form.observaciones,p_estado:form.estado,p_insumos:lineas.map(x=>({insumo_id:x.insumo_id||null,lote_insumo_id:x.lote_insumo_id||null,descripcion:x.descripcion,cantidad:Number(x.cantidad),unidad:x.unidad==='cc'?'ml':x.unidad,observaciones:x.observaciones}))});if(rpcError)setError(rpcError.message);else{setSuccess(form.estado==='registrado'?'Procedimiento registrado y stock descontado.':'Borrador guardado sin descontar stock.');setCreating(false);setForm(emptyForm());setLineas([]);await load()}setSaving(false)}
  async function annul(id:string){if(!empresaId||!window.confirm('¿Anular el procedimiento y devolver sus consumos al stock?'))return;setSaving(true);const {error:rpcError}=await supabase.rpc('vet_anular_procedimiento',{p_empresa_id:empresaId,p_procedimiento_id:id});if(rpcError)setError(rpcError.message);else{setSuccess('Procedimiento anulado y stock restituido.');await load()}setSaving(false)}
  const badge=(state:string)=>`rounded-full px-2.5 py-1 text-xs font-semibold ${state==='registrado'?'bg-emerald-100 text-emerald-800':state==='anulado'?'bg-red-100 text-red-800':'bg-amber-100 text-amber-800'}`

  return <ModuleAccessGuard moduleKey="haras"><main className="min-h-full bg-slate-50 px-4 py-8 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl">
    <header className="rounded-3xl bg-slate-950 px-6 py-8 text-white sm:flex sm:items-center sm:justify-between sm:px-10"><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-emerald-300">Tralixia Haras</p><h1 className="mt-2 text-3xl font-semibold">Procedimientos veterinarios</h1><p className="mt-2 text-sm text-slate-300">Atenciones clínicas, protocolos y consumo seguro de lotes.</p></div><div className="mt-5 flex gap-3 sm:mt-0"><Link href="/haras" className="rounded-xl border border-slate-600 px-4 py-2.5 text-sm font-semibold">Volver a Haras</Link><button onClick={()=>setCreating(true)} className="rounded-xl bg-emerald-500 px-4 py-2.5 text-sm font-semibold text-slate-950">Nuevo procedimiento</button></div></header>
    {error&&<div role="alert" className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</div>}{success&&<div role="status" className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{success}</div>}
    {creating&&<form onSubmit={save} className="mt-6 rounded-2xl border border-emerald-200 bg-white p-6 shadow-sm"><div className="flex justify-between"><div><h2 className="text-xl font-semibold">Registrar procedimiento</h2><p className="mt-1 text-sm text-slate-500">Los registrados descuentan stock atómicamente; los borradores no.</p></div><button type="button" onClick={()=>setCreating(false)} className="text-sm text-slate-600">Cerrar</button></div><div className="mt-5 grid gap-4 md:grid-cols-3">
      <label>Animal *<select required className={field} value={form.animal_id} onChange={e=>setForm({...form,animal_id:e.target.value})}><option value="">Seleccionar</option>{animales.filter(x=>x.estado==='activo').map(x=><option key={x.id} value={x.id}>{x.nombre}{x.identificador?` · ${x.identificador}`:''}</option>)}</select></label><label>Fecha *<input required type="date" className={field} value={form.fecha} onChange={e=>setForm({...form,fecha:e.target.value})}/></label><label>Tipo *<select required className={field} value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value})}>{tipos.map(x=><option key={x}>{title(x)}</option>)}</select></label>
      <label>Protocolo (opcional)<select className={field} value={form.protocolo_id} onChange={e=>selectProtocol(e.target.value)}><option value="">Sin protocolo</option>{protocolos.filter(x=>x.activo).map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select></label><label>Profesional / veterinario<input className={field} value={form.profesional} onChange={e=>setForm({...form,profesional:e.target.value})}/></label><label>Próximo control<input type="date" min={form.fecha} className={field} value={form.proximo_control} onChange={e=>setForm({...form,proximo_control:e.target.value})}/></label>
      <label className="md:col-span-3">Diagnóstico o motivo<textarea rows={2} className={field} value={form.diagnostico} onChange={e=>setForm({...form,diagnostico:e.target.value})}/></label><label className="md:col-span-3">Detalle técnico<textarea rows={3} className={field} value={form.detalle} onChange={e=>setForm({...form,detalle:e.target.value})}/></label><label className="md:col-span-3">Observaciones<textarea rows={2} className={field} value={form.observaciones} onChange={e=>setForm({...form,observaciones:e.target.value})}/></label>
    </div><div className="mt-6 flex items-center justify-between"><div><h3 className="font-semibold">Insumos y acciones</h3><p className="text-xs text-slate-500">También puedes agregar una acción manual sin insumo ni descuento.</p></div><button type="button" onClick={()=>setLineas([...lineas,emptyLine()])} className="rounded-xl bg-sky-800 px-4 py-2 text-sm font-semibold text-white">Agregar ítem</button></div>
    <div className="mt-3 space-y-3">{lineas.map(line=>{const available=lotes.filter(x=>x.insumo_id===line.insumo_id&&x.activo&&x.cantidad_actual>0),selected=lotes.find(x=>x.id===line.lote_insumo_id);return <div key={line.key} className="grid gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4 md:grid-cols-6"><label>Insumo<select className={field} value={line.insumo_id} onChange={e=>selectInsumo(line,e.target.value)}><option value="">Acción manual</option>{insumos.filter(x=>x.activo).map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select></label><label>Lote{line.insumo_id&&' *'}<select className={field} value={line.lote_insumo_id} onChange={e=>updateLine(line.key,{lote_insumo_id:e.target.value})}><option value="">Seleccionar</option>{available.map(x=><option key={x.id} value={x.id}>{x.numero_lote} · {x.cantidad_actual} {x.unidad}</option>)}</select>{selected&&<span className={`text-xs ${selected.fecha_vencimiento&&selected.fecha_vencimiento<form.fecha?'font-semibold text-red-700':'text-slate-500'}`}>Stock {selected.cantidad_actual}; vence {date(selected.fecha_vencimiento)}</span>}</label><label>Cantidad *<input required type="number" min="0.001" max={selected?.cantidad_actual} step="0.001" className={field} value={line.cantidad} onChange={e=>updateLine(line.key,{cantidad:e.target.value})}/></label><label>Unidad<select className={field} value={line.unidad} onChange={e=>updateLine(line.key,{unidad:e.target.value})}>{unidades.map(x=><option key={x}>{x}</option>)}</select></label><label>Costo estimado<div className="mt-1 py-2.5 font-semibold">{money(lineCost(line))}</div></label><button type="button" onClick={()=>setLineas(lineas.filter(x=>x.key!==line.key))} className="self-center text-sm font-semibold text-red-700">Eliminar</button><label className="md:col-span-3">Descripción<input required={!line.insumo_id} className={field} value={line.descripcion} onChange={e=>updateLine(line.key,{descripcion:e.target.value})}/></label><label className="md:col-span-3">Observaciones<input className={field} value={line.observaciones} onChange={e=>updateLine(line.key,{observaciones:e.target.value})}/></label></div>})}</div>
    <div className="mt-6 flex flex-wrap items-end justify-between gap-4 rounded-xl bg-slate-900 p-4 text-white"><div><span className="text-sm text-slate-300">Costo total estimado</span><strong className="block text-2xl">{money(estimated)}</strong></div><label>Estado<select className={`${field} text-slate-900`} value={form.estado} onChange={e=>setForm({...form,estado:e.target.value as Form['estado']})}><option value="registrado">Registrado (descuenta stock)</option><option value="borrador">Borrador (sin descuento)</option></select></label><button disabled={saving} className="rounded-xl bg-emerald-500 px-5 py-3 font-semibold text-slate-950 disabled:opacity-50">{saving?'Guardando…':'Guardar procedimiento'}</button></div></form>}
    <section className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{loading?<p className="p-8 text-center text-slate-500">Cargando…</p>:procedimientos.length===0?<p className="p-10 text-center text-slate-500">Aún no hay procedimientos registrados.</p>:<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-100"><tr>{['Fecha','Animal','Tipo','Protocolo','Profesional','Insumos','Costo total','Próximo control','Estado','Acciones'].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{procedimientos.map(p=><tr key={p.id}><td className="px-4 py-3">{date(p.fecha)}</td><td className="px-4 py-3 font-semibold">{animalNames.get(p.animal_id)}</td><td className="px-4 py-3">{title(p.tipo)}</td><td className="px-4 py-3">{p.protocolo_id?protocolNames.get(p.protocolo_id):'—'}</td><td className="px-4 py-3">{p.profesional??'—'}</td><td className="px-4 py-3">{usos.filter(x=>x.procedimiento_id===p.id).length}</td><td className="px-4 py-3 font-semibold">{money(p.costo_total)}</td><td className="px-4 py-3">{date(p.proximo_control)}</td><td className="px-4 py-3"><span className={badge(p.estado)}>{title(p.estado)}</span></td><td className="px-4 py-3"><div className="flex gap-3"><button onClick={()=>setDetailId(p.id)} className="font-semibold text-sky-700">Ver detalle</button>{p.estado==='registrado'&&<button disabled={saving} onClick={()=>void annul(p.id)} className="font-semibold text-red-700">Anular</button>}</div></td></tr>)}</tbody></table></div>}</section>
    {detail&&<aside className="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex justify-between"><div><p className="text-sm font-semibold uppercase tracking-wider text-emerald-700">Detalle del procedimiento</p><h2 className="mt-1 text-2xl font-semibold">{animalNames.get(detail.animal_id)} · {title(detail.tipo)}</h2></div><button onClick={()=>setDetailId(null)} className="text-sm text-slate-600">Cerrar</button></div><dl className="mt-5 grid gap-4 rounded-xl bg-slate-50 p-4 text-sm sm:grid-cols-4"><div><dt className="text-slate-500">Fecha</dt><dd className="font-semibold">{date(detail.fecha)}</dd></div><div><dt className="text-slate-500">Protocolo</dt><dd className="font-semibold">{detail.protocolo_id?protocolNames.get(detail.protocolo_id):'Sin protocolo'}</dd></div><div><dt className="text-slate-500">Profesional</dt><dd className="font-semibold">{detail.profesional??'—'}</dd></div><div><dt className="text-slate-500">Próximo control</dt><dd className="font-semibold">{date(detail.proximo_control)}</dd></div></dl><div className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><p><strong>Diagnóstico / motivo:</strong> {detail.diagnostico??'—'}</p><p><strong>Detalle técnico:</strong> {detail.detalle??'—'}</p><p className="sm:col-span-2"><strong>Observaciones:</strong> {detail.observaciones??'—'}</p></div><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-100"><tr>{['Ítem','Lote','Cantidad','Unidad','Costo unitario','Costo total','Observaciones'].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody>{detailUsos.map(x=><tr key={x.id} className="border-t border-slate-100"><td className="px-4 py-3 font-semibold">{x.insumo_id?insumoNames.get(x.insumo_id):x.descripcion??'Acción manual'}</td><td className="px-4 py-3">{x.lote_insumo_id?loteNames.get(x.lote_insumo_id):'—'}</td><td className="px-4 py-3">{x.cantidad}</td><td className="px-4 py-3">{x.unidad??'—'}</td><td className="px-4 py-3">{money(x.costo_unitario??0)}</td><td className="px-4 py-3">{money(x.costo_total??0)}</td><td className="px-4 py-3">{x.observaciones??'—'}</td></tr>)}</tbody><tfoot><tr className="border-t-2 border-slate-200"><td colSpan={5} className="px-4 py-3 text-right font-semibold">Costo total general</td><td className="px-4 py-3 text-lg font-bold">{money(detail.costo_total)}</td><td/></tr></tfoot></table></div></aside>}
  </div></main></ModuleAccessGuard>
}
