'use client'

import Link from 'next/link'
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import ModuleAccessGuard from '@/components/ModuleAccessGuard'
import { supabase } from '@/lib/supabase/client'

const EMPRESA_KEY = 'empresa_activa_id'
const tipos = ['vacuna', 'vulvoplastia', 'curacion', 'tratamiento', 'desparasitacion', 'otro'] as const
const categorias = ['todos', 'cria', 'año', 'yegua', 'potro', 'chileno', 'otro'] as const
const eventos = ['monta', 'nacimiento', 'procedimiento', 'fecha_fija', 'otro'] as const
const unidades = ['ml', 'cc', 'unidad', 'dosis', 'gramo', 'litro', 'frasco', 'caja', 'otro'] as const

type Protocolo = { id:string; nombre:string; tipo:string; descripcion:string|null; categoria_aplicable:string|null; periodicidad_dias:number|null; evento_base:string|null; dias_desde_evento:number|null; instrucciones:string|null; activo:boolean }
type Item = { id:string; protocolo_id:string; insumo_id:string|null; descripcion:string; dosis:number|null; unidad:string|null; orden:number; obligatorio:boolean; observaciones:string|null }
type Insumo = { id:string; nombre:string; unidad_medida:string; activo:boolean }
type ProtocoloForm = { nombre:string; tipo:string; descripcion:string; categoria_aplicable:string; periodicidad_dias:string; evento_base:string; dias_desde_evento:string; instrucciones:string; activo:boolean }
type ItemForm = { insumo_id:string; descripcion:string; dosis:string; unidad:string; obligatorio:boolean; orden:string; observaciones:string }

const emptyProtocol: ProtocoloForm = { nombre:'', tipo:'tratamiento', descripcion:'', categoria_aplicable:'todos', periodicidad_dias:'', evento_base:'', dias_desde_evento:'', instrucciones:'', activo:true }
const emptyItem = (orden=1): ItemForm => ({ insumo_id:'', descripcion:'', dosis:'', unidad:'ml', obligatorio:true, orden:String(orden), observaciones:'' })
const field = 'mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-100'
const label = (value:string|null) => value ? value.replaceAll('_',' ').replace(/^./, letter=>letter.toUpperCase()) : '—'

export default function ProtocolosPage() {
  const [empresaId,setEmpresaId]=useState<string|null>(null)
  const [protocolos,setProtocolos]=useState<Protocolo[]>([]), [items,setItems]=useState<Item[]>([]), [insumos,setInsumos]=useState<Insumo[]>([])
  const [loading,setLoading]=useState(true), [saving,setSaving]=useState(false), [error,setError]=useState<string|null>(null), [success,setSuccess]=useState<string|null>(null)
  const [protocolForm,setProtocolForm]=useState<ProtocoloForm>(emptyProtocol), [itemForm,setItemForm]=useState<ItemForm>(emptyItem())
  const [editingId,setEditingId]=useState<string|null>(null), [detailId,setDetailId]=useState<string|null>(null), [formMode,setFormMode]=useState<'protocol'|'item'|null>(null)

  useEffect(()=>{const timer=window.setTimeout(()=>setEmpresaId(localStorage.getItem(EMPRESA_KEY)),0);return()=>window.clearTimeout(timer)},[])
  const load=useCallback(async()=>{
    if(!empresaId){setLoading(false);return}
    setLoading(true);setError(null)
    const [p,i,s]=await Promise.all([
      supabase.from('vet_protocolos').select('id,nombre,tipo,descripcion,categoria_aplicable,periodicidad_dias,evento_base,dias_desde_evento,instrucciones,activo').eq('empresa_id',empresaId).order('nombre'),
      supabase.from('vet_protocolos_items').select('id,protocolo_id,insumo_id,descripcion,dosis,unidad,orden,obligatorio,observaciones').eq('empresa_id',empresaId).order('orden'),
      supabase.from('vet_insumos').select('id,nombre,unidad_medida,activo').eq('empresa_id',empresaId).order('nombre'),
    ])
    const failure=p.error||i.error||s.error
    if(failure)setError(`No fue posible cargar los protocolos: ${failure.message}`)
    else {setProtocolos((p.data??[]) as Protocolo[]);setItems((i.data??[]).map(x=>({...x,dosis:x.dosis==null?null:Number(x.dosis),orden:Number(x.orden)})) as Item[]);setInsumos((s.data??[]) as Insumo[])}
    setLoading(false)
  },[empresaId])
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load])

  const itemCounts=useMemo(()=>items.reduce((counts,item)=>counts.set(item.protocolo_id,(counts.get(item.protocolo_id)??0)+1),new Map<string,number>()),[items])
  const insumoNames=useMemo(()=>new Map(insumos.map(i=>[i.id,i.nombre])),[insumos])
  const detail=protocolos.find(p=>p.id===detailId)??null
  const detailItems=items.filter(i=>i.protocolo_id===detailId).sort((a,b)=>a.orden-b.orden)

  function openProtocol(protocol?:Protocolo){setError(null);setEditingId(protocol?.id??null);setProtocolForm(protocol?{nombre:protocol.nombre,tipo:protocol.tipo,descripcion:protocol.descripcion??'',categoria_aplicable:protocol.categoria_aplicable??'',periodicidad_dias:protocol.periodicidad_dias==null?'':String(protocol.periodicidad_dias),evento_base:protocol.evento_base??'',dias_desde_evento:protocol.dias_desde_evento==null?'':String(protocol.dias_desde_evento),instrucciones:protocol.instrucciones??'',activo:protocol.activo}:emptyProtocol);setFormMode('protocol')}
  function openItem(protocolId:string){const next=Math.max(0,...items.filter(i=>i.protocolo_id===protocolId).map(i=>i.orden))+1;setDetailId(protocolId);setItemForm(emptyItem(next));setError(null);setFormMode('item')}
  function closeForm(){setFormMode(null);setEditingId(null)}
  function selectInsumo(id:string){const insumo=insumos.find(i=>i.id===id);setItemForm({...itemForm,insumo_id:id,descripcion:itemForm.descripcion||insumo?.nombre||'',unidad:insumo?.unidad_medida==='cc'?'ml':insumo?.unidad_medida||itemForm.unidad})}

  async function saveProtocol(event:FormEvent){
    event.preventDefault();if(!empresaId)return
    const periodicidad=protocolForm.periodicidad_dias===''?null:Number(protocolForm.periodicidad_dias), dias=protocolForm.dias_desde_evento===''?null:Number(protocolForm.dias_desde_evento)
    if(!protocolForm.nombre.trim()||!protocolForm.tipo)return setError('Nombre y tipo son obligatorios.')
    if(periodicidad!==null&&periodicidad<=0)return setError('La periodicidad debe ser mayor a 0.')
    if(dias!==null&&dias<0)return setError('Los días desde el evento deben ser mayores o iguales a 0.')
    setSaving(true);setError(null)
    const payload={empresa_id:empresaId,nombre:protocolForm.nombre.trim(),tipo:protocolForm.tipo,descripcion:protocolForm.descripcion.trim()||null,categoria_aplicable:protocolForm.categoria_aplicable||null,periodicidad_dias:periodicidad,evento_base:protocolForm.evento_base||null,dias_desde_evento:dias,instrucciones:protocolForm.instrucciones.trim()||null,activo:protocolForm.activo,updated_at:new Date().toISOString()}
    const result=editingId?await supabase.from('vet_protocolos').update(payload).eq('empresa_id',empresaId).eq('id',editingId):await supabase.from('vet_protocolos').insert(payload)
    if(result.error)setError(result.error.message);else{setSuccess(editingId?'Protocolo actualizado.':'Protocolo creado.');closeForm();await load()}setSaving(false)
  }
  async function saveItem(event:FormEvent){
    event.preventDefault();if(!empresaId||!detailId)return
    const dosis=itemForm.dosis===''?null:Number(itemForm.dosis), orden=Number(itemForm.orden)
    if(!itemForm.descripcion.trim())return setError('La descripción del ítem es obligatoria.')
    if(dosis!==null&&dosis<0)return setError('La dosis o cantidad no puede ser negativa.')
    if(!Number.isInteger(orden)||orden<=0)return setError('El orden debe ser un entero mayor a 0.')
    setSaving(true);setError(null)
    const result=await supabase.from('vet_protocolos_items').insert({empresa_id:empresaId,protocolo_id:detailId,insumo_id:itemForm.insumo_id||null,descripcion:itemForm.descripcion.trim(),dosis,unidad:itemForm.unidad==='cc'?'ml':itemForm.unidad,obligatorio:itemForm.obligatorio,orden,observaciones:itemForm.observaciones.trim()||null})
    if(result.error)setError(result.error.message);else{setSuccess('Ítem agregado al protocolo.');setFormMode(null);await load()}setSaving(false)
  }
  const typeBadge=(type:string)=>`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${type==='vacuna'?'bg-sky-100 text-sky-800':type==='vulvoplastia'?'bg-violet-100 text-violet-800':type==='desparasitacion'?'bg-amber-100 text-amber-800':'bg-emerald-100 text-emerald-800'}`

  return <ModuleAccessGuard moduleKey="haras"><main className="min-h-full bg-slate-50 px-4 py-8 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl">
    <header className="rounded-3xl bg-slate-950 px-6 py-8 text-white sm:flex sm:items-center sm:justify-between sm:px-10"><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-emerald-300">Tralixia Haras</p><h1 className="mt-2 text-3xl font-semibold">Protocolos veterinarios</h1><p className="mt-2 text-sm text-slate-300">Plantillas técnicas reutilizables, sin consumo de stock ni programación automática.</p></div><div className="mt-5 flex gap-3 sm:mt-0"><Link href="/haras" className="rounded-xl border border-slate-600 px-4 py-2.5 text-sm font-semibold">Volver a Haras</Link><button onClick={()=>openProtocol()} className="rounded-xl bg-emerald-500 px-4 py-2.5 text-sm font-semibold text-slate-950">Nuevo protocolo</button></div></header>
    {error&&<div role="alert" className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</div>}{success&&<div role="status" className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{success}</div>}
    {formMode==='protocol'&&<section className="mt-6 rounded-2xl border border-emerald-200 bg-white p-6 shadow-sm"><div className="flex justify-between"><h2 className="text-xl font-semibold">{editingId?'Editar protocolo':'Crear protocolo'}</h2><button onClick={closeForm} className="text-sm text-slate-600">Cerrar</button></div><form onSubmit={saveProtocol} className="mt-5 grid gap-4 md:grid-cols-3"><label>Nombre *<input required className={field} value={protocolForm.nombre} onChange={e=>setProtocolForm({...protocolForm,nombre:e.target.value})}/></label><label>Tipo *<select required className={field} value={protocolForm.tipo} onChange={e=>setProtocolForm({...protocolForm,tipo:e.target.value})}>{tipos.map(x=><option key={x} value={x}>{label(x)}</option>)}</select></label><label>Categoría aplicable<select className={field} value={protocolForm.categoria_aplicable} onChange={e=>setProtocolForm({...protocolForm,categoria_aplicable:e.target.value})}><option value="">Sin especificar</option>{categorias.map(x=><option key={x}>{x}</option>)}</select></label><label>Periodicidad (días)<input type="number" min="1" className={field} value={protocolForm.periodicidad_dias} onChange={e=>setProtocolForm({...protocolForm,periodicidad_dias:e.target.value})}/></label><label>Evento base<select className={field} value={protocolForm.evento_base} onChange={e=>setProtocolForm({...protocolForm,evento_base:e.target.value})}><option value="">Sin evento</option>{eventos.map(x=><option key={x} value={x}>{label(x)}</option>)}</select></label><label>Días desde evento<input type="number" min="0" className={field} value={protocolForm.dias_desde_evento} onChange={e=>setProtocolForm({...protocolForm,dias_desde_evento:e.target.value})}/></label><label className="md:col-span-3">Descripción<textarea rows={2} className={field} value={protocolForm.descripcion} onChange={e=>setProtocolForm({...protocolForm,descripcion:e.target.value})}/></label><label className="md:col-span-3">Instrucciones<textarea rows={3} className={field} value={protocolForm.instrucciones} onChange={e=>setProtocolForm({...protocolForm,instrucciones:e.target.value})}/></label><label className="flex items-center gap-2"><input type="checkbox" checked={protocolForm.activo} onChange={e=>setProtocolForm({...protocolForm,activo:e.target.checked})}/> Activo</label><button disabled={saving} className="rounded-xl bg-emerald-600 px-4 py-2.5 font-semibold text-white disabled:opacity-50">{saving?'Guardando…':'Guardar protocolo'}</button></form></section>}
    {formMode==='item'&&<section className="mt-6 rounded-2xl border border-sky-200 bg-white p-6 shadow-sm"><div className="flex justify-between"><h2 className="text-xl font-semibold">Agregar ítem a {detail?.nombre}</h2><button onClick={closeForm} className="text-sm text-slate-600">Cerrar</button></div><form onSubmit={saveItem} className="mt-5 grid gap-4 md:grid-cols-3"><label>Insumo (opcional)<select className={field} value={itemForm.insumo_id} onChange={e=>selectInsumo(e.target.value)}><option value="">Acción manual / sin insumo</option>{insumos.filter(i=>i.activo).map(i=><option key={i.id} value={i.id}>{i.nombre}</option>)}</select></label><label>Descripción *<input required className={field} value={itemForm.descripcion} onChange={e=>setItemForm({...itemForm,descripcion:e.target.value})}/></label><label>Dosis / cantidad<input type="number" min="0" step="0.001" className={field} value={itemForm.dosis} onChange={e=>setItemForm({...itemForm,dosis:e.target.value})}/></label><label>Unidad<select className={field} value={itemForm.unidad} onChange={e=>setItemForm({...itemForm,unidad:e.target.value})}>{unidades.map(x=><option key={x}>{x}</option>)}</select><span className="text-xs text-slate-500">cc se guarda como ml.</span></label><label>Orden *<input required type="number" min="1" step="1" className={field} value={itemForm.orden} onChange={e=>setItemForm({...itemForm,orden:e.target.value})}/></label><label className="flex items-center gap-2 pt-7"><input type="checkbox" checked={itemForm.obligatorio} onChange={e=>setItemForm({...itemForm,obligatorio:e.target.checked})}/> Ítem obligatorio</label><label className="md:col-span-3">Observaciones<textarea rows={2} className={field} value={itemForm.observaciones} onChange={e=>setItemForm({...itemForm,observaciones:e.target.value})}/></label><button disabled={saving} className="rounded-xl bg-sky-700 px-4 py-2.5 font-semibold text-white disabled:opacity-50">{saving?'Guardando…':'Agregar ítem'}</button></form></section>}
    <section className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{loading?<p className="p-8 text-center text-slate-500">Cargando…</p>:protocolos.length===0?<div className="p-10 text-center"><h2 className="font-semibold text-slate-900">Aún no hay protocolos</h2><p className="mt-2 text-sm text-slate-500">Crea una plantilla de vacuna, tratamiento u otro procedimiento.</p></div>:<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-100 text-slate-700"><tr>{['Nombre','Tipo','Categoría','Periodicidad','Evento base','Días evento','Insumos','Estado','Acciones'].map(x=><th key={x} className="px-4 py-3 font-semibold">{x}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{protocolos.map(p=><tr key={p.id} className={!p.activo?'bg-slate-50 text-slate-500':''}><td className="px-4 py-3 font-semibold text-slate-900">{p.nombre}</td><td className="px-4 py-3"><span className={typeBadge(p.tipo)}>{label(p.tipo)}</span></td><td className="px-4 py-3">{label(p.categoria_aplicable)}</td><td className="px-4 py-3">{p.periodicidad_dias??'—'}</td><td className="px-4 py-3">{label(p.evento_base)}</td><td className="px-4 py-3">{p.dias_desde_evento??'—'}</td><td className="px-4 py-3 font-semibold">{itemCounts.get(p.id)??0}</td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${p.activo?'bg-emerald-100 text-emerald-800':'bg-slate-200 text-slate-700'}`}>{p.activo?'Activo':'Inactivo'}</span></td><td className="px-4 py-3"><div className="flex flex-wrap gap-3"><button onClick={()=>openProtocol(p)} className="font-semibold text-sky-700">Editar</button><button onClick={()=>{setDetailId(p.id);setFormMode(null)}} className="font-semibold text-slate-700">Ver detalle</button><button onClick={()=>openItem(p.id)} className="font-semibold text-emerald-700">Agregar insumo</button></div></td></tr>)}</tbody></table></div>}</section>
    {detail&&<aside className="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-wider text-emerald-700">Detalle del protocolo</p><h2 className="mt-1 text-2xl font-semibold text-slate-900">{detail.nombre}</h2><p className="mt-2 text-sm text-slate-600">{detail.descripcion||'Sin descripción.'}</p></div><div className="flex gap-3"><button onClick={()=>openItem(detail.id)} className="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-semibold text-white">Agregar ítem</button><button onClick={()=>setDetailId(null)} className="rounded-xl border border-slate-300 px-4 py-2 text-sm font-semibold">Cerrar</button></div></div><dl className="mt-5 grid gap-4 rounded-xl bg-slate-50 p-4 text-sm sm:grid-cols-4"><div><dt className="text-slate-500">Tipo</dt><dd className="font-semibold">{label(detail.tipo)}</dd></div><div><dt className="text-slate-500">Categoría</dt><dd className="font-semibold">{label(detail.categoria_aplicable)}</dd></div><div><dt className="text-slate-500">Programación</dt><dd className="font-semibold">{detail.periodicidad_dias?`Cada ${detail.periodicidad_dias} días`:'Sin periodicidad'}</dd></div><div><dt className="text-slate-500">Estado</dt><dd className="font-semibold">{detail.activo?'Activo':'Inactivo'}</dd></div></dl>{detail.instrucciones&&<div className="mt-4 rounded-xl border border-slate-200 p-4 text-sm"><strong>Instrucciones:</strong> {detail.instrucciones}</div>}<div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-100"><tr>{['Orden','Ítem / insumo','Dosis','Unidad','Carácter','Observaciones'].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{detailItems.map(item=><tr key={item.id}><td className="px-4 py-3">{item.orden}</td><td className="px-4 py-3 font-semibold">{item.descripcion}<div className="text-xs font-normal text-slate-500">{item.insumo_id?insumoNames.get(item.insumo_id)??'Insumo no disponible':'Acción manual'}</div></td><td className="px-4 py-3">{item.dosis??'—'}</td><td className="px-4 py-3">{item.unidad??'—'}</td><td className="px-4 py-3">{item.obligatorio?'Obligatorio':'Opcional'}</td><td className="px-4 py-3">{item.observaciones??'—'}</td></tr>)}{detailItems.length===0&&<tr><td colSpan={6} className="px-4 py-8 text-center text-slate-500">Este protocolo aún no tiene ítems.</td></tr>}</tbody></table></div></aside>}
  </div></main></ModuleAccessGuard>
}
