-- Piloto PTS: base multiempresa, seguridad y flujo digital.
-- No crea empresas ni usuarios; solo prepara el modulo y sus datos.

begin;

alter table public.empresa_modulos
  drop constraint if exists empresa_modulos_modulo_check;

alter table public.empresa_modulos
  add constraint empresa_modulos_modulo_check
  check (modulo = any (array[
    'comercial'::text,
    'financiero'::text,
    'contable'::text,
    'operacional'::text,
    'rrhh'::text,
    'administracion'::text,
    'haras'::text,
    'seguridad'::text
  ]));

alter table public.usuario_empresas
  drop constraint if exists usuario_empresas_rol_check;

alter table public.usuario_empresas
  add constraint usuario_empresas_rol_check
  check (rol = any (array[
    'admin'::text,
    'administracion_financiera'::text,
    'cobranzas'::text,
    'comercial'::text,
    'tecnico_ot'::text,
    'demo_cliente'::text,
    'seguridad_pts'::text
  ]));

create or replace function public.usuario_tiene_acceso_pts(p_empresa_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    public.es_super_admin()
    or exists (
      select 1
      from public.usuario_empresas ue
      join public.empresa_modulos em
        on em.empresa_id = ue.empresa_id
       and em.modulo = 'seguridad'
       and em.habilitado = true
      where ue.empresa_id = p_empresa_id
        and ue.usuario_id = auth.uid()
        and coalesce(ue.activo, true) = true
        and ue.rol in ('admin', 'seguridad_pts')
    );
$$;

create table if not exists public.pts_permisos (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  folio bigint generated by default as identity,
  estado text not null default 'borrador'
    check (estado in ('borrador','en_revision','observado','aprobado','en_ejecucion','cerrado','rechazado')),
  trabajo_a_realizar text not null,
  tipo_actividad text not null,
  lugar_ejecucion text not null,
  empresa_contratista text not null,
  fecha_inicio date not null,
  fecha_termino date,
  hora_inicio time,
  hora_termino time,
  observaciones text,
  enviado_revision_at timestamptz,
  aprobado_at timestamptz,
  iniciado_at timestamptz,
  cerrado_at timestamptz,
  created_by uuid default auth.uid() references public.perfiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, empresa_id)
);

create index if not exists pts_permisos_empresa_estado_idx
  on public.pts_permisos (empresa_id, estado, fecha_inicio desc);

create table if not exists public.pts_analisis_riesgos (
  id uuid primary key default gen_random_uuid(),
  permiso_id uuid not null,
  empresa_id uuid not null,
  paso smallint not null check (paso > 0 and paso <= 20),
  actividad text not null,
  peligros text not null,
  riesgos text not null,
  medidas_preventivas text not null,
  orden integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (permiso_id, empresa_id)
    references public.pts_permisos(id, empresa_id)
    on delete cascade
);

create index if not exists pts_analisis_permiso_idx
  on public.pts_analisis_riesgos (permiso_id, orden, paso);

create table if not exists public.pts_personal (
  id uuid primary key default gen_random_uuid(),
  permiso_id uuid not null,
  empresa_id uuid not null,
  nombre_apellido text not null,
  rut text not null,
  induccion_ingreso_ok boolean not null default false,
  charla_5_min_ok boolean not null default false,
  examen_altura_vigente_hasta date,
  orden integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (permiso_id, empresa_id)
    references public.pts_permisos(id, empresa_id)
    on delete cascade
);

create index if not exists pts_personal_permiso_idx
  on public.pts_personal (permiso_id, orden);

create table if not exists public.pts_epp (
  id uuid primary key default gen_random_uuid(),
  permiso_id uuid not null,
  empresa_id uuid not null,
  codigo text not null,
  nombre text not null,
  requerido boolean not null default true,
  orden integer not null default 0,
  created_at timestamptz not null default now(),
  foreign key (permiso_id, empresa_id)
    references public.pts_permisos(id, empresa_id)
    on delete cascade,
  unique (permiso_id, codigo)
);

create table if not exists public.pts_aprobaciones (
  id uuid primary key default gen_random_uuid(),
  permiso_id uuid not null,
  empresa_id uuid not null,
  etapa text not null
    check (etapa in ('supervisor_contratista','coordinador_contratista','jefatura_area','seguridad')),
  estado text not null default 'pendiente'
    check (estado in ('pendiente','aprobado','observado','rechazado')),
  nombre_firmante text,
  cargo_firmante text,
  usuario_id uuid references public.perfiles(id),
  observacion text,
  firmado_at timestamptz,
  orden integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (permiso_id, empresa_id)
    references public.pts_permisos(id, empresa_id)
    on delete cascade,
  unique (permiso_id, etapa)
);

create table if not exists public.pts_historial (
  id uuid primary key default gen_random_uuid(),
  permiso_id uuid not null,
  empresa_id uuid not null,
  evento text not null,
  detalle text,
  usuario_id uuid default auth.uid() references public.perfiles(id),
  created_at timestamptz not null default now(),
  foreign key (permiso_id, empresa_id)
    references public.pts_permisos(id, empresa_id)
    on delete cascade
);

create index if not exists pts_historial_permiso_idx
  on public.pts_historial (permiso_id, created_at desc);

create or replace function public.pts_set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists pts_permisos_set_updated_at on public.pts_permisos;
create trigger pts_permisos_set_updated_at
before update on public.pts_permisos
for each row execute function public.pts_set_updated_at();

drop trigger if exists pts_analisis_set_updated_at on public.pts_analisis_riesgos;
create trigger pts_analisis_set_updated_at
before update on public.pts_analisis_riesgos
for each row execute function public.pts_set_updated_at();

drop trigger if exists pts_personal_set_updated_at on public.pts_personal;
create trigger pts_personal_set_updated_at
before update on public.pts_personal
for each row execute function public.pts_set_updated_at();

drop trigger if exists pts_aprobaciones_set_updated_at on public.pts_aprobaciones;
create trigger pts_aprobaciones_set_updated_at
before update on public.pts_aprobaciones
for each row execute function public.pts_set_updated_at();

alter table public.pts_permisos enable row level security;
alter table public.pts_analisis_riesgos enable row level security;
alter table public.pts_personal enable row level security;
alter table public.pts_epp enable row level security;
alter table public.pts_aprobaciones enable row level security;
alter table public.pts_historial enable row level security;

drop policy if exists pts_permisos_empresa_access on public.pts_permisos;
create policy pts_permisos_empresa_access
on public.pts_permisos
for all
to authenticated
using (public.usuario_tiene_acceso_pts(empresa_id))
with check (public.usuario_tiene_acceso_pts(empresa_id));

drop policy if exists pts_analisis_empresa_access on public.pts_analisis_riesgos;
create policy pts_analisis_empresa_access
on public.pts_analisis_riesgos
for all
to authenticated
using (public.usuario_tiene_acceso_pts(empresa_id))
with check (public.usuario_tiene_acceso_pts(empresa_id));

drop policy if exists pts_personal_empresa_access on public.pts_personal;
create policy pts_personal_empresa_access
on public.pts_personal
for all
to authenticated
using (public.usuario_tiene_acceso_pts(empresa_id))
with check (public.usuario_tiene_acceso_pts(empresa_id));

drop policy if exists pts_epp_empresa_access on public.pts_epp;
create policy pts_epp_empresa_access
on public.pts_epp
for all
to authenticated
using (public.usuario_tiene_acceso_pts(empresa_id))
with check (public.usuario_tiene_acceso_pts(empresa_id));

drop policy if exists pts_aprobaciones_empresa_access on public.pts_aprobaciones;
create policy pts_aprobaciones_empresa_access
on public.pts_aprobaciones
for all
to authenticated
using (public.usuario_tiene_acceso_pts(empresa_id))
with check (public.usuario_tiene_acceso_pts(empresa_id));

drop policy if exists pts_historial_empresa_access on public.pts_historial;
create policy pts_historial_empresa_access
on public.pts_historial
for all
to authenticated
using (public.usuario_tiene_acceso_pts(empresa_id))
with check (public.usuario_tiene_acceso_pts(empresa_id));

grant select, insert, update, delete on
  public.pts_permisos,
  public.pts_analisis_riesgos,
  public.pts_personal,
  public.pts_epp,
  public.pts_aprobaciones,
  public.pts_historial
to authenticated;

grant usage, select on sequence public.pts_permisos_folio_seq to authenticated;

commit;
