'use client'

import Link from 'next/link'
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import ModuleAccessGuard from '@/components/ModuleAccessGuard'
import { supabase } from '@/lib/supabase/client'

const EMPRESA_KEY = 'empresa_activa_id'
const tipos = ['medicamento', 'vacuna', 'material', 'suplemento', 'equipo', 'otro'] as const
const unidades = ['ml', 'cc', 'unidad', 'dosis', 'gramo', 'litro', 'frasco', 'caja', 'otro'] as const
type Tab = 'insumos' | 'proveedores' | 'lotes' | 'alertas'
type Insumo = { id:string; nombre:string; tipo:string; unidad_medida:string; presentacion:string|null; stock_minimo:number; costo_referencial:number|null; observaciones:string|null; activo:boolean }
type Proveedor = { id:string; nombre:string; identificacion_fiscal:string|null; contacto:string|null; telefono:string|null; email:string|null; direccion:string|null; observaciones:string|null; activo:boolean }
type Lote = { id:string; insumo_id:string; proveedor_id:string|null; numero_lote:string; fecha_compra:string; fecha_vencimiento:string|null; cantidad_inicial:number; cantidad_actual:number; unidad:string|null; costo_total:number|null; costo_unitario:number|null; observaciones:string|null; activo:boolean }
type InsumoForm = { nombre:string; tipo:string; unidad_medida:string; presentacion:string; stock_minimo:string; costo_referencial:string; observaciones:string; activo:boolean }
type ProveedorForm = { nombre:string; identificacion_fiscal:string; contacto:string; telefono:string; email:string; direccion:string; observaciones:string; activo:boolean }
type LoteForm = { insumo_id:string; proveedor_id:string; numero_lote:string; fecha_compra:string; fecha_vencimiento:string; cantidad_inicial:string; cantidad_actual:string; unidad:string; costo_total:string; observaciones:string }

const hoy = () => new Date().toISOString().slice(0, 10)
const emptyInsumo: InsumoForm = { nombre:'', tipo:'medicamento', unidad_medida:'ml', presentacion:'', stock_minimo:'0', costo_referencial:'', observaciones:'', activo:true }
const emptyProveedor: ProveedorForm = { nombre:'', identificacion_fiscal:'', contacto:'', telefono:'', email:'', direccion:'', observaciones:'', activo:true }
const emptyLote = (): LoteForm => ({ insumo_id:'', proveedor_id:'', numero_lote:'', fecha_compra:hoy(), fecha_vencimiento:'', cantidad_inicial:'', cantidad_actual:'', unidad:'ml', costo_total:'', observaciones:'' })
const field = 'mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-100'
const money = (value:number|null) => value == null ? '—' : new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:2}).format(value)
const date = (value:string|null) => value ? new Intl.DateTimeFormat('es-CL').format(new Date(`${value}T00:00:00`)) : '—'
const num = (value:unknown) => Number(value ?? 0)

export default function InsumosPage() {
  const [empresaId,setEmpresaId]=useState<string|null>(null), [tab,setTab]=useState<Tab>('insumos')
  const [insumos,setInsumos]=useState<Insumo[]>([]), [proveedores,setProveedores]=useState<Proveedor[]>([]), [lotes,setLotes]=useState<Lote[]>([])
  const [loading,setLoading]=useState(true), [saving,setSaving]=useState(false), [error,setError]=useState<string|null>(null), [success,setSuccess]=useState<string|null>(null)
  const [dialog,setDialog]=useState<'insumo'|'proveedor'|'lote'|null>(null), [editingId,setEditingId]=useState<string|null>(null)
  const [insumoForm,setInsumoForm]=useState(emptyInsumo), [proveedorForm,setProveedorForm]=useState(emptyProveedor), [loteForm,setLoteForm]=useState<LoteForm>(emptyLote)

  useEffect(()=>{const timer=window.setTimeout(()=>setEmpresaId(localStorage.getItem(EMPRESA_KEY)),0);return()=>window.clearTimeout(timer)},[])
  const load = useCallback(async()=>{
    if(!empresaId){setLoading(false);return}
    setLoading(true); setError(null)
    const [i,p,l]=await Promise.all([
      supabase.from('vet_insumos').select('id,nombre,tipo,unidad_medida,presentacion,stock_minimo,costo_referencial,observaciones,activo').eq('empresa_id',empresaId).order('nombre'),
      supabase.from('vet_proveedores').select('id,nombre,identificacion_fiscal,contacto,telefono,email,direccion,observaciones,activo').eq('empresa_id',empresaId).order('nombre'),
      supabase.from('vet_lotes_insumo').select('id,insumo_id,proveedor_id,numero_lote,fecha_compra,fecha_vencimiento,cantidad_inicial,cantidad_actual,unidad,costo_total,costo_unitario,observaciones,activo').eq('empresa_id',empresaId).order('fecha_compra',{ascending:false}),
    ])
    const failure=i.error||p.error||l.error
    if(failure)setError(`No fue posible cargar los datos: ${failure.message}`)
    else {setInsumos((i.data??[]).map(x=>({...x,stock_minimo:num(x.stock_minimo),costo_referencial:x.costo_referencial==null?null:num(x.costo_referencial)})) as Insumo[]);setProveedores((p.data??[]) as Proveedor[]);setLotes((l.data??[]).map(x=>({...x,cantidad_inicial:num(x.cantidad_inicial),cantidad_actual:num(x.cantidad_actual),costo_total:x.costo_total==null?null:num(x.costo_total),costo_unitario:x.costo_unitario==null?null:num(x.costo_unitario)})) as Lote[])}
    setLoading(false)
  },[empresaId])
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load])

  const stats=useMemo(()=>new Map(insumos.map(i=>{
    const own=lotes.filter(l=>l.insumo_id===i.id&&l.activo), valid=own.filter(l=>!l.fecha_vencimiento||l.fecha_vencimiento>=hoy())
    const stock=valid.reduce((s,l)=>s+l.cantidad_actual,0), expired=own.some(l=>!!l.fecha_vencimiento&&l.fecha_vencimiento<hoy()&&l.cantidad_actual>0)
    const limit=new Date();limit.setDate(limit.getDate()+30);const limitDate=limit.toISOString().slice(0,10)
    const expiring=valid.some(l=>!!l.fecha_vencimiento&&l.fecha_vencimiento<=limitDate&&l.cantidad_actual>0)
    const next=[...valid].filter(l=>l.fecha_vencimiento&&l.cantidad_actual>0).sort((a,b)=>(a.fecha_vencimiento??'').localeCompare(b.fecha_vencimiento??''))[0]?.fecha_vencimiento??null
    const costs=valid.filter(l=>l.costo_unitario!=null), avg=costs.length?costs.reduce((s,l)=>s+(l.costo_unitario??0)*l.cantidad_actual,0)/(costs.reduce((s,l)=>s+l.cantidad_actual,0)||costs.length):i.costo_referencial
    const status=stock<=0?'Sin stock':expired?'Vencido':expiring?'Próximo a vencer':stock<=i.stock_minimo?'Bajo stock':'OK'
    return [i.id,{stock,next,avg,status,expired,expiring}]
  })),[insumos,lotes])
  const names=useMemo(()=>new Map(insumos.map(i=>[i.id,i.nombre])),[insumos]), providerNames=useMemo(()=>new Map(proveedores.map(p=>[p.id,p.nombre])),[proveedores])
  const alerts=insumos.filter(i=>stats.get(i.id)?.status!=='OK')
  function notice(message:string){setSuccess(message);setError(null);setDialog(null);setEditingId(null)}
  function openInsumo(i?:Insumo){setEditingId(i?.id??null);setInsumoForm(i?{nombre:i.nombre,tipo:i.tipo,unidad_medida:i.unidad_medida,presentacion:i.presentacion??'',stock_minimo:String(i.stock_minimo),costo_referencial:i.costo_referencial==null?'':String(i.costo_referencial),observaciones:i.observaciones??'',activo:i.activo}:emptyInsumo);setDialog('insumo')}
  function openProveedor(p?:Proveedor){setEditingId(p?.id??null);setProveedorForm(p?{nombre:p.nombre,identificacion_fiscal:p.identificacion_fiscal??'',contacto:p.contacto??'',telefono:p.telefono??'',email:p.email??'',direccion:p.direccion??'',observaciones:p.observaciones??'',activo:p.activo}:emptyProveedor);setDialog('proveedor')}
  function openLote(insumoId=''){setEditingId(null);setLoteForm({...emptyLote(),insumo_id:insumoId,unidad:insumos.find(i=>i.id===insumoId)?.unidad_medida??'ml'});setDialog('lote')}
  async function saveInsumo(e:FormEvent){e.preventDefault();if(!empresaId||!insumoForm.nombre.trim())return setError('Nombre, tipo y unidad base son obligatorios.');if(num(insumoForm.stock_minimo)<0)return setError('El stock mínimo no puede ser negativo.');setSaving(true)
    const payload={empresa_id:empresaId,nombre:insumoForm.nombre.trim(),tipo:insumoForm.tipo,unidad_medida:insumoForm.unidad_medida==='cc'?'ml':insumoForm.unidad_medida,presentacion:insumoForm.presentacion.trim()||null,stock_minimo:num(insumoForm.stock_minimo),costo_referencial:insumoForm.costo_referencial===''?null:num(insumoForm.costo_referencial),observaciones:insumoForm.observaciones.trim()||null,activo:insumoForm.activo,updated_at:new Date().toISOString()}
    const r=editingId?await supabase.from('vet_insumos').update(payload).eq('empresa_id',empresaId).eq('id',editingId):await supabase.from('vet_insumos').insert(payload);if(r.error)setError(r.error.message);else{notice(editingId?'Insumo actualizado.':'Insumo creado.');await load()}setSaving(false)}
  async function saveProveedor(e:FormEvent){e.preventDefault();if(!empresaId||!proveedorForm.nombre.trim())return setError('El nombre del proveedor es obligatorio.');setSaving(true);const payload={empresa_id:empresaId,nombre:proveedorForm.nombre.trim(),identificacion_fiscal:proveedorForm.identificacion_fiscal.trim()||null,contacto:proveedorForm.contacto.trim()||null,telefono:proveedorForm.telefono.trim()||null,email:proveedorForm.email.trim()||null,direccion:proveedorForm.direccion.trim()||null,observaciones:proveedorForm.observaciones.trim()||null,activo:proveedorForm.activo,updated_at:new Date().toISOString()};const r=editingId?await supabase.from('vet_proveedores').update(payload).eq('empresa_id',empresaId).eq('id',editingId):await supabase.from('vet_proveedores').insert(payload);if(r.error)setError(r.error.message);else{notice(editingId?'Proveedor actualizado.':'Proveedor creado.');await load()}setSaving(false)}
  async function saveLote(e:FormEvent){e.preventDefault();if(!empresaId||!loteForm.insumo_id||!loteForm.proveedor_id||!loteForm.fecha_compra||!loteForm.numero_lote.trim())return setError('Insumo, proveedor, fecha de compra y lote son obligatorios.');const initial=num(loteForm.cantidad_inicial),actual=loteForm.cantidad_actual===''?initial:num(loteForm.cantidad_actual),cost=num(loteForm.costo_total);if(initial<=0||actual<0||cost<0)return setError('Cantidad inicial debe ser mayor a 0; cantidad actual y costo no pueden ser negativos.');setSaving(true);const r=await supabase.from('vet_lotes_insumo').insert({empresa_id:empresaId,insumo_id:loteForm.insumo_id,proveedor_id:loteForm.proveedor_id,numero_lote:loteForm.numero_lote.trim(),fecha_ingreso:loteForm.fecha_compra,fecha_compra:loteForm.fecha_compra,fecha_vencimiento:loteForm.fecha_vencimiento||null,cantidad_inicial:initial,cantidad_actual:actual,unidad:loteForm.unidad==='cc'?'ml':loteForm.unidad,costo_total:cost,observaciones:loteForm.observaciones.trim()||null});if(r.error)setError(r.error.message);else{notice('Compra/lote registrado y stock actualizado.');await load()}setSaving(false)}
  const badge=(status:string)=>`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${status==='OK'?'bg-emerald-100 text-emerald-800':status==='Sin stock'||status==='Vencido'?'bg-red-100 text-red-800':status==='Bajo stock'?'bg-amber-100 text-amber-800':'bg-orange-100 text-orange-800'}`

  return <ModuleAccessGuard moduleKey="haras"><main className="min-h-full bg-slate-50 px-4 py-8 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl">
    <header className="rounded-3xl bg-slate-950 px-6 py-8 text-white sm:flex sm:items-center sm:justify-between sm:px-10"><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-emerald-300">Tralixia Haras</p><h1 className="mt-2 text-3xl font-semibold">Insumos y stock real</h1><p className="mt-2 text-sm text-slate-300">Medicamentos, proveedores, compras, lotes y vencimientos.</p></div><div className="mt-5 flex gap-3 sm:mt-0"><Link href="/haras" className="rounded-xl border border-slate-600 px-4 py-2.5 text-sm font-semibold">Volver a Haras</Link><button onClick={()=>openInsumo()} className="rounded-xl bg-emerald-500 px-4 py-2.5 text-sm font-semibold text-slate-950">Nuevo insumo</button></div></header>
    {error&&<div role="alert" className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</div>}{success&&<div role="status" className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{success}</div>}
    <nav className="mt-6 flex flex-wrap gap-2" aria-label="Secciones">{([['insumos','Insumos / medicamentos'],['proveedores','Proveedores'],['lotes','Lotes / compras'],['alertas',`Stock y alertas (${alerts.length})`]] as [Tab,string][]).map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={`rounded-xl px-4 py-2 text-sm font-semibold ${tab===key?'bg-slate-900 text-white':'border border-slate-200 bg-white text-slate-700'}`}>{label}</button>)}</nav>
    {dialog&&<section className="mt-6 rounded-2xl border border-emerald-200 bg-white p-6 shadow-sm"><div className="flex justify-between"><h2 className="text-xl font-semibold">{editingId?'Editar ':dialog==='lote'?'Registrar compra / lote':'Nuevo '}{dialog}</h2><button onClick={()=>setDialog(null)} className="text-sm text-slate-600">Cerrar</button></div>
      {dialog==='insumo'&&<form onSubmit={saveInsumo} className="mt-5 grid gap-4 md:grid-cols-3"><label>Nombre *<input required className={field} value={insumoForm.nombre} onChange={e=>setInsumoForm({...insumoForm,nombre:e.target.value})}/></label><label>Tipo *<select className={field} value={insumoForm.tipo} onChange={e=>setInsumoForm({...insumoForm,tipo:e.target.value})}>{tipos.map(x=><option key={x}>{x}</option>)}</select></label><label>Unidad base *<select className={field} value={insumoForm.unidad_medida} onChange={e=>setInsumoForm({...insumoForm,unidad_medida:e.target.value})}>{unidades.map(x=><option key={x}>{x}</option>)}</select></label><label>Presentación<input className={field} placeholder="Frasco 100 ml" value={insumoForm.presentacion} onChange={e=>setInsumoForm({...insumoForm,presentacion:e.target.value})}/></label><label>Stock mínimo<input type="number" min="0" step="0.001" className={field} value={insumoForm.stock_minimo} onChange={e=>setInsumoForm({...insumoForm,stock_minimo:e.target.value})}/></label><label>Costo referencial<input type="number" min="0" step="0.01" className={field} value={insumoForm.costo_referencial} onChange={e=>setInsumoForm({...insumoForm,costo_referencial:e.target.value})}/></label><label className="md:col-span-3">Observaciones<textarea className={field} value={insumoForm.observaciones} onChange={e=>setInsumoForm({...insumoForm,observaciones:e.target.value})}/></label><label className="flex items-center gap-2"><input type="checkbox" checked={insumoForm.activo} onChange={e=>setInsumoForm({...insumoForm,activo:e.target.checked})}/> Activo</label><button disabled={saving} className="rounded-xl bg-emerald-600 px-4 py-2 text-white">Guardar</button></form>}
      {dialog==='proveedor'&&<form onSubmit={saveProveedor} className="mt-5 grid gap-4 md:grid-cols-3">{([['nombre','Nombre *'],['identificacion_fiscal','RUT'],['contacto','Contacto'],['telefono','Teléfono'],['email','Email'],['direccion','Dirección']] as [keyof ProveedorForm,string][]).map(([k,label])=><label key={k}>{label}<input required={k==='nombre'} type={k==='email'?'email':'text'} className={field} value={String(proveedorForm[k])} onChange={e=>setProveedorForm({...proveedorForm,[k]:e.target.value})}/></label>)}<label className="md:col-span-3">Observaciones<textarea className={field} value={proveedorForm.observaciones} onChange={e=>setProveedorForm({...proveedorForm,observaciones:e.target.value})}/></label><label className="flex items-center gap-2"><input type="checkbox" checked={proveedorForm.activo} onChange={e=>setProveedorForm({...proveedorForm,activo:e.target.checked})}/> Activo (desactivar conserva el histórico)</label><button disabled={saving} className="rounded-xl bg-emerald-600 px-4 py-2 text-white">Guardar</button></form>}
      {dialog==='lote'&&<form onSubmit={saveLote} className="mt-5 grid gap-4 md:grid-cols-3"><label>Insumo *<select required className={field} value={loteForm.insumo_id} onChange={e=>{const id=e.target.value;setLoteForm({...loteForm,insumo_id:id,unidad:insumos.find(i=>i.id===id)?.unidad_medida??'ml'})}}><option value="">Seleccionar</option>{insumos.filter(i=>i.activo).map(i=><option key={i.id} value={i.id}>{i.nombre}</option>)}</select></label><label>Proveedor *<select required className={field} value={loteForm.proveedor_id} onChange={e=>setLoteForm({...loteForm,proveedor_id:e.target.value})}><option value="">Seleccionar</option>{proveedores.filter(p=>p.activo).map(p=><option key={p.id} value={p.id}>{p.nombre}</option>)}</select></label><label>Número de lote *<input required className={field} value={loteForm.numero_lote} onChange={e=>setLoteForm({...loteForm,numero_lote:e.target.value})}/></label><label>Fecha compra *<input required type="date" className={field} value={loteForm.fecha_compra} onChange={e=>setLoteForm({...loteForm,fecha_compra:e.target.value})}/></label><label>Vencimiento<input type="date" className={field} value={loteForm.fecha_vencimiento} onChange={e=>setLoteForm({...loteForm,fecha_vencimiento:e.target.value})}/></label><label>Unidad<select className={field} value={loteForm.unidad} onChange={e=>setLoteForm({...loteForm,unidad:e.target.value})}>{unidades.map(x=><option key={x}>{x}</option>)}</select></label><label>Cantidad inicial *<input required type="number" min="0.001" step="0.001" className={field} value={loteForm.cantidad_inicial} onChange={e=>setLoteForm({...loteForm,cantidad_inicial:e.target.value,cantidad_actual:e.target.value})}/></label><label>Cantidad actual<input type="number" min="0" step="0.001" className={field} value={loteForm.cantidad_actual} onChange={e=>setLoteForm({...loteForm,cantidad_actual:e.target.value})}/></label><label>Costo total *<input required type="number" min="0" step="0.01" className={field} value={loteForm.costo_total} onChange={e=>setLoteForm({...loteForm,costo_total:e.target.value})}/></label><label className="md:col-span-3">Observaciones<textarea className={field} value={loteForm.observaciones} onChange={e=>setLoteForm({...loteForm,observaciones:e.target.value})}/></label><p className="text-sm text-slate-500 md:col-span-2">El costo unitario se calcula como costo total ÷ cantidad inicial. cc se normaliza a ml.</p><button disabled={saving} className="rounded-xl bg-emerald-600 px-4 py-2 text-white">Registrar compra</button></form>}
    </section>}
    <section className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{loading?<p className="p-8 text-center text-slate-500">Cargando…</p>:<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-100 text-slate-700"><tr>{(tab==='proveedores'?['Proveedor','RUT / contacto','Contacto','Estado','Acciones']:tab==='lotes'?['Insumo / lote','Proveedor','Compra','Vencimiento','Stock','Costo unitario']:['Insumo','Tipo / unidad','Stock actual','Stock mínimo','Costo promedio','Próximo vencimiento','Estado','Acciones']).map(x=><th key={x} className="px-4 py-3 font-semibold">{x}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">
      {(tab==='insumos'||tab==='alertas')&&(tab==='alertas'?alerts:insumos).map(i=>{const s=stats.get(i.id)!;return <tr key={i.id} className={!i.activo?'opacity-60':''}><td className="px-4 py-3 font-semibold">{i.nombre}<div className="text-xs font-normal text-slate-500">{i.presentacion}</div></td><td className="px-4 py-3">{i.tipo}<div className="text-xs text-slate-500">{i.unidad_medida}</div></td><td className="px-4 py-3 font-semibold">{s.stock.toLocaleString('es-CL')} {i.unidad_medida}</td><td className="px-4 py-3">{i.stock_minimo}</td><td className="px-4 py-3">{money(s.avg)}</td><td className="px-4 py-3">{date(s.next)}</td><td className="px-4 py-3"><span className={badge(s.status)}>{s.status}</span></td><td className="px-4 py-3"><div className="flex gap-2"><button onClick={()=>openInsumo(i)} className="font-semibold text-sky-700">Editar</button><button onClick={()=>openLote(i.id)} className="font-semibold text-emerald-700">Comprar</button><button onClick={()=>setTab('lotes')} className="font-semibold text-slate-700">Ver lotes</button></div></td></tr>})}
      {tab==='proveedores'&&proveedores.map(p=><tr key={p.id} className={!p.activo?'opacity-60':''}><td className="px-4 py-3 font-semibold">{p.nombre}</td><td className="px-4 py-3">{p.identificacion_fiscal??'—'}<div className="text-xs text-slate-500">{p.contacto}</div></td><td className="px-4 py-3">{p.telefono??'—'}<div className="text-xs text-slate-500">{p.email}</div></td><td className="px-4 py-3">{p.activo?'Activo':'Inactivo'}</td><td className="px-4 py-3"><button onClick={()=>openProveedor(p)} className="font-semibold text-sky-700">Editar</button></td></tr>)}
      {tab==='lotes'&&lotes.map(l=>{const expired=!!l.fecha_vencimiento&&l.fecha_vencimiento<hoy();return <tr key={l.id}><td className="px-4 py-3 font-semibold">{names.get(l.insumo_id)}<div className="text-xs text-slate-500">Lote {l.numero_lote}</div></td><td className="px-4 py-3">{l.proveedor_id?providerNames.get(l.proveedor_id):'—'}</td><td className="px-4 py-3">{date(l.fecha_compra)}</td><td className={`px-4 py-3 ${expired?'font-semibold text-red-700':''}`}>{date(l.fecha_vencimiento)}{expired&&' · Vencido'}</td><td className="px-4 py-3">{l.cantidad_actual} {l.unidad}</td><td className="px-4 py-3">{money(l.costo_unitario)}</td></tr>})}
    </tbody></table></div>}</section>
    <div className="mt-5 flex gap-3">{tab==='proveedores'&&<button onClick={()=>openProveedor()} className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Nuevo proveedor</button>}{tab==='lotes'&&<button onClick={()=>openLote()} className="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white">Registrar compra / lote</button>}</div>
  </div></main></ModuleAccessGuard>
}
